# Generated by Django 3.1.2 on 2021-08-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kakeibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('opt', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=200)),
                ('suuji', models.IntegerField()),
            ],
        ),
    ]
